name: Deploy Vue to Alibaba Cloud (pnpm)

on:
  push:
    branches: ['release']

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # 安装 pnpm
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8 # 指定pnpm版本（与本地一致）

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm' # 启用pnpm专属缓存

      # 安装依赖（使用pnpm）
      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile # 严格依赖lockfile

      # 构建项目
      - name: Build project
        run: pnpm run build

      # 部署到阿里云
      - name: Deploy to Server
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: '47.93.81.21'
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_SSH_PORT }}
          script: |
            find /www/wwwroot/47.93.81.21/BUAA-PracticeTeam/ -type f -not -name '.user.ini' -delete
            mv /github/workspace/dist/* /www/wwwroot/47.93.81.21/BUAA-PracticeTeam/
            sudo nginx -t && sudo systemctl restart nginx
